apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tap-demo-liquibase
  labels:
    app.kubernetes.io/part-of: tap-demo-liquibase
    apps.tanzu.vmware.com/has-db-migrations: "true"
    apps.tanzu.vmware.com/workload-type: web
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/min-scale: "1"
    - name: gitops_server_address
      value: ssh://git@github.com
    - name: gitops_repository_owner
      value: th3n3rd
    - name: gitops_repository_name
      value: tap-demo-liquibase-gitops
    - name: gitops_branch
      value: dev
    - name: gitops_commit_message
      value: "Update tap-demo-liquibase config"
    - name: gitops_ssh_secret
      value: tap-gitops-ssh-auth
    - name: db_migrations_path
      value: ./src/main/resources/db/changelog
    - name: db_migrations_service_claim_name
      value: db-migrations
  source:
    git:
      url: ssh://git@github.com/th3n3rd/tap-demo-liquibase.git
      ref:
        branch: main
  env:
    - name: spring.liquibase.enabled
      value: "false"
  serviceClaims:
    - name: db
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ClassClaim
        name: tap-demo-liquibase-db
    - name: db-migrations
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ClassClaim
        name: tap-demo-liquibase-db
