apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tap-demo-liquibase
  labels:
    app.kubernetes.io/part-of: tap-demo-liquibase
    apps.tanzu.vmware.com/workload-type: web
spec:
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
  source:
    git:
      url: https://github.com/th3n3rd/tap-demo-liquibase.git
      ref:
        branch: main
