apiVersion: carto.run/v1alpha1
kind: ClusterConfigTemplate
metadata:
  name: liquibase-config-provider-template
spec:
  configPath: '.status.taskResults[?(@.name=="liquibase-config-base64")].value'
  lifecycle: tekton
  ytt: |
    #@ load("@ytt:data", "data")
    
    #@ def merge_labels(fixed_values):
    #@   labels = {}
    #@   if hasattr(data.values.workload.metadata, "labels"):
    #@     labels.update(data.values.workload.metadata.labels)
    #@   end
    #@   labels.update(fixed_values)
    #@   return labels
    #@ end
    ---
    apiVersion: tekton.dev/v1beta1
    kind: TaskRun
    metadata:
      generateName: #@ data.values.workload.metadata.name + "-liquibase-config-provider-"
      labels: #@ merge_labels({ "app.kubernetes.io/component": "liquibase-config-provider" })
    spec:
      params:
        - name: source-url
          value: #@ data.values.source.url
        - name: source-revision
          value: #@ data.values.source.revision
        - name: workload-name
          value: #@ data.values.workload.metadata.name
        - name: db-migrations-path
          value: #@ data.values.params.db_migrations_path
      serviceAccountName: #@ data.values.params.serviceAccount
      taskSpec:
          description: |-
            A task that takes the liquibase migrations found in a given git repository and encoded them into a YAML and then base64.
          params:
            - name: source-url
            - name: source-revision
            - name: workload-name
            - name: db-migrations-path
          steps:
            - name: serialise-db-migrations
              image: ghcr.io/vmware-tanzu/carvel-docker-image@sha256:5ab82a2ac0b983f5967b5ffc7d3503b4741ac808cd2c1cc6b4a42916f7ed1a47
              script: |
                #!/usr/bin/env bash
                cd `mktemp -d`
                wget -qO- $(params.source-url) | tar xvz -m
                touch plain-config.yaml
                for file in $(params.db-migrations-path)
                do
                  echo "`basename $file`: |" >> plain-config.yaml
                  sed 's/^/    /' "$file" >> plain-config.yaml
                done
                cat plain-config.yaml | base64 > $(results.liquibase-config-base64.path)
          results:
            - name: liquibase-config-base64
              description: base64-encoded YAML describing the liquibase database migrations
